### ISSUE TITLE
certbot-dns plugin

### ISSUE THREAD

**Issue by ltmichael** [jlesage/docker-nginx-proxy-manager#125]
Hello!

Thank you for updating NPM to the latest version to add the DNS challenge! I'm running into some issues when using the DNS challenge. I receive this error:

Error: Command failed: pip3 install certbot-dns-cloudflare==1.8.0
/bin/sh: pip3: not found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket. (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe. (net.js:674:12)

**Comment by ltmichael** [comment]
duplicate submission by accident.
