### ISSUE TITLE
pip3 install

### ISSUE THREAD

**Issue by ltmichael** [jlesage/docker-nginx-proxy-manager#126]
Hello!

Thank you for updating NPM to the latest version to add the DNS challenge! I'm running into some issues when using the DNS challenge. I receive this error:

`Error: Command failed: pip3 install certbot-dns-cloudflare==1.8.0
/bin/sh: pip3: not found
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket. (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe. (net.js:674:12)`

**Comment by jlesage** [comment]
Ahh I though that I had verified that `pip3` was part of the image...  I will fix it.
As a workaround, you can add it by executing `docker exec <container name> add-pkg py3-pip`.

**Comment by ltmichael** [comment]
No problem! I executed that command and now I'm receiving:
`Error: Command failed: pip3 install certbot-dns-cloudflare==1.8.0
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '\n'
Check the permissions.


    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`

**Comment by jlesage** [comment]
Ok please try the latest version, it should work now.  Let me know if you still have issues.

**Comment by ltmichael** [comment]
Yes, it works! I was able to use cloudflare dns challenges to generate LE certs. Thank you so much!
