### ISSUE TITLE
certbot outdated

### ISSUE THREAD

**Issue by nielscil** [jlesage/docker-nginx-proxy-manager#163]
Hi,

I was trying to add a Let's Encrypt Certificate  using the dns directadmin plugin. It seems that the plugin needs a higher version of certbot.

```
Error: Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "<cert>" --agree-tos --email "<email>" --domains "<domain>" --authenticator certbot-dns-directadmin:directadmin --certbot-dns-directadmin:directadmin-credentials "<creds>" --certbot-dns-directadmin:directadmin-propagation-seconds 240
An unexpected error occurred:
pkg_resources.VersionConflict: (certbot 1.4.0 (/usr/lib/python3.8/site-packages), Requirement.parse('certbot<1.8.0,>=1.7.0'))
Please see the logfile '/tmp/tmpu9v4l207/log' for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by R0GGER** [comment]
Ehh... DirectAdmin? Are you lost?

**Comment by jlesage** [comment]
Latest certbot version used in latest image.
