### ISSUE TITLE
Cant generate Certs anymore

### ISSUE THREAD

**Issue by Coow** [jlesage/docker-nginx-proxy-manager#217]
Restarted both Container and Host in hopes but nothing 
`Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-39" --agree-tos --authenticator webroot --email "" --preferred-challenges "dns,http" --domains "subdomain.mrcow.xyz"
Another instance of Certbot is already running.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/tmpjmp2ayq7/log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`

Is the contents of the Log file

`2021-11-10 19:02:15,079:DEBUG:certbot._internal.main:certbot version: 1.21.0
2021-11-10 19:02:15,079:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2021-11-10 19:02:15,079:DEBUG:certbot._internal.main:Arguments: ['--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-39', '--agree-tos', '--authenticator', 'webroot', '--email', '', '--preferred-challenges', 'dns,http', '--domains', 'subdomain.mrcow.xyz']
2021-11-10 19:02:15,079:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-11-10 19:02:15,090:DEBUG:certbot._internal.lock:A lock on /var/log/letsencrypt/.certbot.lock is held by another process.
2021-11-10 19:02:15,090:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/lock.py", line 126, in _try_lock
    fcntl.lockf(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1558, in main
    log.post_arg_parse_setup(config)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/log.py", line 100, in post_arg_parse_setup
    file_handler, file_path = setup_log_file_handler(
  File "/usr/lib/python3.8/site-packages/certbot/_internal/log.py", line 153, in setup_log_file_handler
    util.set_up_core_dir(config.logs_dir, 0o700, config.strict_permissions)
  File "/usr/lib/python3.8/site-packages/certbot/util.py", line 178, in set_up_core_dir
    lock_dir_until_exit(directory)
  File "/usr/lib/python3.8/site-packages/certbot/util.py", line 152, in lock_dir_until_exit
    _LOCKS[dir_path] = lock.lock_dir(dir_path)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/lock.py", line 258, in lock_dir
    return LockFile(os.path.join(dir_path, '.certbot.lock'))
  File "/usr/lib/python3.8/site-packages/certbot/_internal/lock.py", line 45, in __init__
    self.acquire()
  File "/usr/lib/python3.8/site-packages/certbot/_internal/lock.py", line 60, in acquire
    self._lock_mechanism.acquire()
  File "/usr/lib/python3.8/site-packages/certbot/_internal/lock.py", line 112, in acquire
    self._try_lock(fd)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/lock.py", line 130, in _try_lock
    raise errors.LockError('Another instance of Certbot is already running.')
certbot.errors.LockError: Another instance of Certbot is already running.
2021-11-10 19:02:15,090:ERROR:certbot._internal.log:Another instance of Certbot is already running.`

**Comment by cpt-n3mo** [comment]
having the same problem here while renewing Certs
any workaround on this one..?

**Comment by timowevel1** [comment]
Same here

**Comment by smailpouri** [comment]
same here. 

were you guys able to solve this?

**Comment by fschindo** [comment]
Same Problem

**Comment by Angel-Dijoux** [comment]
Same here

**Comment by Angel-Dijoux** [comment]
Ok ! I found a solution.
I use docker (Docker version 23.0.1, build a5ee5b1)

I went to the terminal of my container, I installed procps : 

`apt install update && apt upgrade -y && apt install procps`

I get `certbot` process with : `ps -eaf | grep "certbot"`
I killed all the processes and I restart the generation of the certficat from the web interface of NPM

**Comment by idoodler** [comment]
The only process I can find is the grep process
