### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by tuccler** [jlesage/docker-nginx-proxy-manager#220]
I get the "Internal Error" Message when I'm trying to renew my certificates.
If i want to create a new certificate i get this:

> Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-19" --agree-tos --authenticator webroot --email "julian@xxx.eu" --preferred-challenges "dns,http" --domains "test.xxx.eu" 
> An unexpected error occurred:
> pkg_resources.ContextualVersionConflict: (cryptography 36.0.0 (/usr/lib/python3.8/site-packages), Requirement.parse('cryptography<4,>=0.6'), {'msal'})
> Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/tmpnej7ttvj/log or re-run Certbot with -v for more details.
> 
>     at ChildProcess.exithandler (child_process.js:308:12)
>     at ChildProcess.emit (events.js:314:20)
>     at maybeClose (internal/child_process.js:1022:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

I'm not using the dns challenge at all. Also Port 80 is recheable from the internet and forwarded to nginx-proxy-manager.

How can I repair this? All my certificates are going to expire soon.

**Comment by jlesage** [comment]
Do you have a `.local` directory under the directory you mapped to `/config` ?  If yes, try to remove/rename it and restart the container.

**Comment by Luzl1** [comment]
@dhover 
I am facing the same error: "some challenges have failed".
I can renew the certificates manually if I (temporary) disable the "Force SSL" option. It seems that npm is redirecting the LE-Challenges to Port 443.

Could you solve the problem in the meantime?

**Comment by dhover** [comment]
> Could you solve the problem in the meantime?

Yes but there was nothing wrong with npm. It was a strange problem with the router.
