### ISSUE TITLE
Unable to request certs

### ISSUE THREAD

**Issue by mlewis26201** [jlesage/docker-nginx-proxy-manager#24]
Whenever I try to request a new LetsEncrypt cert, it seems to fail with an error message of "Internal Error", but then lists the cert. Cert is then unusable.

Looking at the log directory, the letsencrypt log shows this:

2019-07-16 16:35:59,452:DEBUG:certbot.main:certbot version: 0.25.1
2019-07-16 16:35:59,453:DEBUG:certbot.main:Arguments: ['-n', '--force-renewal', '--disable-hook-validation', '--cert-name', 'npm-5']
2019-07-16 16:35:59,453:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-07-16 16:35:59,476:DEBUG:certbot.log:Root logging level set at 20
2019-07-16 16:35:59,477:INFO:certbot.log:Saving debug log to /config/log/letsencrypt/letsencrypt.log
2019-07-16 16:35:59,478:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.25.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1323, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1235, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 388, in handle_renewal_request
    conf_files = [storage.renewal_file_for_certname(config, config.certname)]
  File "/usr/lib/python2.7/site-packages/certbot/storage.py", line 49, in renewal_file_for_certname
    "{1}).".format(certname, path))
CertStorageError: No certificate found with name npm-5 (expected /etc/letsencrypt/renewal/npm-5.conf).

**Comment by jlesage** [comment]
Is you container accessible from the Internet on port 80?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if required.
