### ISSUE TITLE
Letsencrypt errors, npm-.conf is broken. Skipping....

### ISSUE THREAD

**Issue by ufo56** [jlesage/docker-nginx-proxy-manager#61]
Hi

My nging proxy manager letsencrypt gives a lot of errors lately and won't update certificates anymore.

```
2020-04-01 11:03:42,243:DEBUG:certbot.main:certbot version: 0.30.2
2020-04-01 11:03:42,245:DEBUG:certbot.main:Arguments: ['--non-interactive', '--quiet', '--config', '/etc/letsencrypt.ini', '--preferred-challenges', 'dns,http', '--disable-hook-validation']
2020-04-01 11:03:42,247:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-04-01 11:03:43,795:DEBUG:certbot.log:Root logging level set at 30
2020-04-01 11:03:43,798:INFO:certbot.log:Saving debug log to /config/log/letsencrypt/letsencrypt.log
2020-04-01 11:03:43,815:WARNING:certbot.renewal:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-2/cert.pem to be a symlink
2020-04-01 11:03:43,817:WARNING:certbot.renewal:Renewal configuration file /etc/letsencrypt/renewal/npm-2.conf is broken. Skipping.
2020-04-01 11:03:43,818:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-2/cert.pem to be a symlink
2020-04-01 11:03:43,847:WARNING:certbot.renewal:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-6/cert.pem to be a symlink
2020-04-01 11:03:43,847:WARNING:certbot.renewal:Renewal configuration file /etc/letsencrypt/renewal/npm-6.conf is broken. Skipping.
2020-04-01 11:03:43,848:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-6/cert.pem to be a symlink

2020-04-01 11:03:43,857:WARNING:certbot.renewal:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-7/cert.pem to be a symlink
2020-04-01 11:03:43,858:WARNING:certbot.renewal:Renewal configuration file /etc/letsencrypt/renewal/npm-7.conf is broken. Skipping.
2020-04-01 11:03:43,859:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-7/cert.pem to be a symlink

2020-04-01 11:03:43,868:WARNING:certbot.renewal:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-4/cert.pem to be a symlink
2020-04-01 11:03:43,869:WARNING:certbot.renewal:Renewal configuration file /etc/letsencrypt/renewal/npm-4.conf is broken. Skipping.
2020-04-01 11:03:43,870:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 461, in __init__
    self._check_symlinks()
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 520, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/npm-4/cert.pem to be a symlink
2020-04-01 11:03:43,977:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer <certbot.cli._Default object at 0x152295b2d940>
2020-04-01 11:03:43,977:DEBUG:certbot.cli:Var pref_challs=dns,http (set by user).
2020-04-01 11:03:43,978:DEBUG:certbot.cli:Var logs_dir=/config/log/letsencrypt (set by user).
2020-04-01 11:03:43,978:DEBUG:certbot.cli:Var work_dir=/config/letsencrypt-workdir (set by user).
2020-04-01 11:03:43,979:DEBUG:certbot.cli:Var authenticator=webroot (set by user).
2020-04-01 11:03:43,979:DEBUG:certbot.cli:Var webroot_path=/data/letsencrypt-acme-challenge (set by user).
2020-04-01 11:03:43,980:DEBUG:certbot.cli:Var webroot_map={'webroot_path'} (set by user).
2020-04-01 11:03:44,096:INFO:certbot.renewal:Cert not yet due for renewal
2020-04-01 11:03:44,110:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2020-04-01 11:03:44,111:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.30.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1271, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 477, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
certbot.errors.Error: 0 renew failure(s), 9 parse failure(s)
```

**Comment by ufo56** [comment]
After deleting certificate and requesting new it works again.
