### ISSUE TITLE
Cannot resolve acme-v02.api.letsencrypt.org

### ISSUE THREAD

**Issue by fstelte** [jlesage/docker-nginx-proxy-manager#95]
I have this running some time. But yesterday wanted to request a certificate for a new subdomain of mine, but received and "internal error" looking at the logs:

Saving debug log to /config/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator webroot, Installer None

An unexpected error occurred:

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn

    (self.host, self.port), self.timeout, **extra_kw)

  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection

    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen

    chunked=chunked)

  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request

    self._validate_conn(conn)

  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn

    conn.connect()

  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect

    conn = self._new_conn()

  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn

    self, "Failed to establish a new connection: %s" % e)

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4e5b54bf60>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send

    timeout=timeout

  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen

    _stacktrace=sys.exc_info()[2])

  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4e5b54bf60>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4e5b54bf60>: Failed to establish a new connection: [Errno -3] Try again',))

Please see the logfiles in /config/log/letsencrypt for more details.

So running from the container I CAN ping the IP of the API but not the FQDN of the API..

**Comment by fstelte** [comment]
Found the issue. On my docker machine two stale DNS servers where still configured... Removed them and now it works
