### ISSUE TITLE
Unable to create new proxied host or renew SSL certificates, receiving "Internal Error"

### ISSUE THREAD

**Issue by odin-bb** [jlesage/docker-nginx-proxy-manager#97]
I am attempting to create new proxied host and when I attempt to create a new one, with an SSL, it gives me an error saying "internal error."  I also noticed that the same thing happens when I attempt to renew a certificate. Checking the logs, I see that auto-renewals isn't working. 

LOG:
at ChildProcess.exithandler (child_process.js:294:12)
at ChildProcess.emit (events.js:198:13)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[7/29/2020] [1:15:10 PM] [Nginx ] › ℹ info Reloading Nginx
[7/29/2020] [1:15:11 PM] [SSL ] › ℹ info Requesting Let'sEncrypt certificates for Cert #40: REDACTED
[7/29/2020] [1:15:21 PM] [Nginx ] › ℹ info Reloading Nginx
[7/29/2020] [1:15:21 PM] [Express ] › ⚠ warning Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-40" --agree-tos --email "REDACTED" --preferred-challenges "dns,http" --webroot --domains "REDACTED"

Unraid
NPM is a docker

**Comment by jlesage** [comment]
This problem is usually due to the container not being reachable from the Internet.  You can use https://canyouseeme.org to confirm if port 80 is accessible.

**Comment by odin-bb** [comment]
Can you see me shows port 80 open. What else can I check?

**Comment by jlesage** [comment]
You can look at files under `/mnt/user/appdata/NginxProxyManager/log/letsencrypt/`, where you should have more details about the failure.

**Comment by Mickroz** [comment]
```
2020-10-13 14:12:32,730:DEBUG:certbot.main:certbot version: 0.30.2
2020-10-13 14:12:32,734:DEBUG:certbot.main:Arguments: ['--non-interactive', '--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-9', '--agree-tos', '--email', 'REDACTED', '--preferred-challenges', 'dns,http', '--webroot', '--domains', 'REDACTED']
2020-10-13 14:12:32,737:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-10-13 14:12:32,810:DEBUG:certbot.log:Root logging level set at 20
2020-10-13 14:12:32,814:INFO:certbot.log:Saving debug log to /config/log/letsencrypt/letsencrypt.log
2020-10-13 14:12:32,817:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2020-10-13 14:12:32,838:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7facbb579a58>
Prep: True
2020-10-13 14:12:32,842:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7facbb579a58> and installer None
2020-10-13 14:12:32,843:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-10-13 14:12:32,879:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/99173305', new_authzr_uri=None, terms_of_service=None), 095836e3eca6ba297a3b571ae4d6d96b, Meta(creation_dt=datetime.datetime(2020, 10, 13, 6, 54, 14, tzinfo=<UTC>), creation_host='fc00d11d563c'))>
2020-10-13 14:12:32,885:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-10-13 14:12:32,893:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
2020-10-13 14:12:33,448:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-10-13 14:12:33,453:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 13 Oct 2020 14:12:33 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "IKHMIDUpEe4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-10-13 14:12:33,455:INFO:certbot.main:Obtaining a new certificate
2020-10-13 14:12:33,980:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0008_key-certbot.pem
2020-10-13 14:12:33,990:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0008_csr-certbot.pem
2020-10-13 14:12:33,992:DEBUG:acme.client:Requesting fresh nonce
2020-10-13 14:12:33,993:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-10-13 14:12:34,124:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-10-13 14:12:34,126:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 13 Oct 2020 14:12:34 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0101ONpye8tIrNLTXE8h0lF6lBp-VFNcl4azvPW0i8z2_pI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-10-13 14:12:34,126:DEBUG:acme.client:Storing nonce: 0101ONpye8tIrNLTXE8h0lF6lBp-VFNcl4azvPW0i8z2_pI
2020-10-13 14:12:34,128:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "REDACTED"\n    }\n  ]\n}'
2020-10-13 14:12:34,140:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTkxNzMzMDUiLCAibm9uY2UiOiAiMDEwMU9OcHllOHRJck5MVFhFOGgwbEY2bEJwLVZGTmNsNGF6dlBXMGk4ejJfcEkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "lv0QcJtSyidGRmKnKVIjAt3kqAxv6dqOhJa0kqUaLApeNaQ10WH-5kqTkjUpwAgw_pDxvcB8jLy1Se1SCqeGXJjS8yNY_wO2Xn6Ke_5d9otZS3j9891bcNsUs06y0AH-OW-Z_5j2wlSYotUh0OIqGldUNPRAegw2OinAPNzh2klPv1UmmqXtqyWce-GOFH5alygDo12S2MpGeopAAENydS6I4dBDOKIlMDxMd99dLS50rKkvo8IaG5uEN9VNnMNy4gWX2SoQGyHZMs799F1KQyFfNGFSGlrbNDSsX3S8UdKecgB1PCZLdUGFk9Qcxvnjz4rIPqALUWDkjRxI1bU-6Q",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImVtYnkud29laWkubmwiCiAgICB9CiAgXQp9"
}
2020-10-13 14:12:34,414:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 201
2020-10-13 14:12:34,419:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Tue, 13 Oct 2020 14:12:34 GMT
Content-Type: application/problem+json
Content-Length: 201
Connection: keep-alive
Boulder-Requester: 99173305
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01028z9mMgvpNf3MRCrl0ihSzEjvZ5reKsQvITsjqF0h9Sc

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
2020-10-13 14:12:34,422:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.30.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1249, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 385, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 870, in new_order
    return self.client.new_order(csr_pem)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 652, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 95, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1185, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1202, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1054, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
2020-10-13 14:12:34,468:ERROR:certbot.log:An unexpected error occurred:
2020-10-13 14:12:34,469:ERROR:certbot.log:There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/

```

**Comment by jlesage** [comment]
@Mickroz, you seem that have been rate limited because of previous failures:
```
"detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
```

If you look at previous logs you should see what were these failures.

**Comment by Mickroz** [comment]
yes the same :P
but i fixed it, somewhere along the line the main domain didn't pointed at my home ip, so all subdomains on that domain failed, because of the dns resolve.
after i fixed the main domain, the requests all passed correctly.
